language: java

before_install:
    - sudo apt-get install python-pip
    - sudo pip install -U requests biopython beautifulsoup4 futures

install:
    - python geo_downloader.py --gid GSE47753
script:
    - python geo_downloader.py
